import { Show } from "@/types";
import poster2 from "@/assets/images/poster2.gif";
import poster10 from "@/assets/images/poster10.gif";
import poster13 from "@/assets/images/poster13.png";

export const initialShowData: Show[] = [
  {
    id: 1,
    posterImage: poster10,
    showType: "무용",
    status: "공연중",
    defaultLiked: true,
    title: "유니버설발레단 (호두까기 인형) - 성남",
    location: "예술의 전당 오페라 극장",
    date: "2024.11.30",
    keywords: ["섬세한", "역동적인", "서정적인", "웅장한", "새로운"],
    isLiked: true,
  },
  {
    id: 2,
    posterImage: poster13,
    showType: "서양음악(클래식)",
    status: "공연중",
    defaultLiked: false,
    title: "대니 구 크리스마스 콘서트 <HOME>",
    location: "예술의 전당 오페라 극장",
    date: "2024.11.30",
    keywords: ["섬세한", "역동적인", "서정적인", "웅장한", "새로운"],
    isLiked: false,
  },
  {
    id: 3,
    posterImage: poster2,
    showType: "무용",
    status: "completed",
    defaultLiked: false,
    title: "라트라비아타",
    location: "예술의 전당 오페라 극장",
    date: "2024.11.30",
    keywords: ["섬세한", "역동적인", "서정적인", "웅장한", "새로운"],
    isLiked: false,
  },
  {
    id: 4,
    posterImage: poster2,
    showType: "무용",
    status: "공연예정",
    defaultLiked: false,
    title: "라트라비아타",
    location: "예술의 전당 오페라 극장",
    date: "2024.11.30",
    keywords: ["섬세한", "역동적인", "서정적인", "웅장한", "새로운"],
    isLiked: false,
  },
  {
    id: 5,
    posterImage: poster2,
    showType: "무용",
    status: "completed",
    defaultLiked: false,
    title: "라트라비아타",
    location: "예술의 전당 오페라 극장",
    date: "2024.11.30",
    keywords: ["섬세한", "역동적인", "서정적인", "웅장한", "새로운"],
    isLiked: false,
  },
  {
    id: 6,
    posterImage: poster2,
    showType: "서양음악(클래식)",
    status: "공연중",
    defaultLiked: false,
    title: "라트라비아타",
    location: "예술의 전당 오페라 극장",
    date: "2024.11.30",
    keywords: ["섬세한", "역동적인", "서정적인", "웅장한", "새로운"],
    isLiked: false,
  },
];

export const searchResultData: Show[] = [
  {
    id: 1,
    posterImage: poster10,
    showType: "무용",
    status: "공연예정",
    defaultLiked: true,
    title: "유니버설발레단 (호두까기 인형) - 성남",
    location: "예술의 전당 오페라 극장",
    date: "2024.11.30",
    keywords: ["섬세한", "역동적인", "서정적인", "웅장한", "새로운"],
    isLiked: true,
  },
];
